# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='From')),
                ('hashCode', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash')),
                ('destination', models.CharField(blank=True, default='', max_length=64, verbose_name='To')),
            ],
        ),
    ]
