# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171110_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default=b'', max_length=64, verbose_name=b'Alias')),
                ('adresse', models.CharField(blank=True, default=b'', max_length=64, verbose_name=b'Adresse')),
            ],
        ),
    ]
